version: "3.9"
services:
  db:
    image: ankane/pgvector:latest
    container_name: medai_db
    environment:
      POSTGRES_USER: medai
      POSTGRES_PASSWORD: medai
      POSTGRES_DB: medai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  redis:
    image: redis:7
    container_name: medai_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
